In [69]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('advertising.csv')
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [70]:
x, y = df[['TV', 'Radio']], df.Sales
x, y, b = np.asarray(x), np.asarray(y), 1
w = np.ones(x.shape[1])
print(x.shape, w.shape)

(200, 2) (2,)

In [71]:
from sklearn.metrics import mean_squared_error as mse
yh = x @ w + b
mse(y, yh)

31243.0201

In [72]:
n = len(y)
dw = -2 * ((y - yh)/n) @ x
dw.shape

(2,)

In [73]:
lr = 3e-5 
limit = 10 ** 5
for i in range(limit):
    dw = -2 * np.dot((y - yh)/n, x)
    db = -2 * (y - yh).mean()
    w = w - np.dot(lr, dw)
    b = b - lr * db
    yh = np.dot(x, w) + b
print(mse(yh, y))

3.0129076517457536

In [13]:
import numpy as np
x = np.random.rand(100,2)
x.shape
x

array([[0.51355717, 0.13364459],
       [0.52627903, 0.84227198],
       [0.10666296, 0.07561942],
       [0.03357455, 0.2497602 ],
       [0.32758457, 0.29611288],
       [0.0884257 , 0.41550459],
       [0.33647615, 0.81515422],
       [0.53521771, 0.35306372],
       [0.43424808, 0.46100245],
       [0.41817898, 0.58557814],
       [0.95213601, 0.05924072],
       [0.87750771, 0.21541726],
       [0.99042983, 0.77888758],
       [0.10177626, 0.59326601],
       [0.69949836, 0.10054012],
       [0.29294295, 0.28160594],
       [0.58435909, 0.50069336],
       [0.83619085, 0.91324508],
       [0.41636281, 0.35566898],
       [0.41922284, 0.84631247],
       [0.59922262, 0.23774737],
       [0.36318704, 0.5518306 ],
       [0.02846336, 0.69692205],
       [0.55767392, 0.31854834],
       [0.38262585, 0.40586819],
       [0.49868469, 0.08332655],
       [0.95989689, 0.81557196],
       [0.46018999, 0.37785032],
       [0.26449121, 0.74862283],
       [0.60305196, 0.78248943],
       [0.26807994, 0.46341413],
       [0.55655332, 0.43556752],
       [0.25821857, 0.16644786],
       [0.09666868, 0.1419949 ],
       [0.11950888, 0.03077929],
       [0.35887274, 0.54557053],
       [0.98764355, 0.73746925],
       [0.50781475, 0.86913191],
       [0.77834621, 0.44107429],
       [0.24336568, 0.56950746],
       [0.79719277, 0.1676819 ],
       [0.61220379, 0.8942702 ],
       [0.81416541, 0.0737247 ],
       [0.45895502, 0.03466083],
       [0.1554274 , 0.0703476 ],
       [0.77694804, 0.46695321],
       [0.40790319, 0.59892621],
       [0.83456214, 0.38305383],
       [0.96388666, 0.14980999],
       [0.13996849, 0.62974446],
       [0.82169352, 0.62410524],
       [0.79743366, 0.11527389],
       [0.99504712, 0.20803427],
       [0.44612882, 0.0325058 ],
       [0.49854409, 0.02866027],
       [0.44416363, 0.28355121],
       [0.19751691, 0.25448535],
       [0.84399796, 0.39172782],
       [0.09832687, 0.79890712],
       [0.56771713, 0.00420104],
       [0.99460406, 0.56005255],
       [0.32959396, 0.00696003],
       [0.50116727, 0.85120959],
       [0.34362445, 0.81356734],
       [0.69399654, 0.83343034],
       [0.30532979, 0.83645204],
       [0.37587657, 0.48804241],
       [0.31075786, 0.13408677],
       [0.36356056, 0.17572356],
       [0.32095287, 0.5920257 ],
       [0.21050566, 0.94548313],
       [0.89443135, 0.84661287],
       [0.52467214, 0.68191531],
       [0.49370784, 0.77105396],
       [0.72054777, 0.15858611],
       [0.71411803, 0.23717775],
       [0.2686569 , 0.64392849],
       [0.17890255, 0.28031325],
       [0.8440534 , 0.02099514],
       [0.00342547, 0.29885829],
       [0.1199014 , 0.98650594],
       [0.5498206 , 0.90647853],
       [0.39974432, 0.57073727],
       [0.96180243, 0.8481084 ],
       [0.90653707, 0.49585359],
       [0.92136704, 0.60758372],
       [0.56652663, 0.25506875],
       [0.04410846, 0.65681645],
       [0.33836958, 0.24422567],
       [0.83517731, 0.75298397],
       [0.60197863, 0.55100415],
       [0.19879941, 0.14706766],
       [0.18614443, 0.5944139 ],
       [0.89839793, 0.58745239],
       [0.84132917, 0.43272558],
       [0.0998158 , 0.89844714],
       [0.03312685, 0.10079499],
       [0.58060924, 0.34961997],
       [0.80941306, 0.73090013],
       [0.35621403, 0.7418688 ]])